using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Lab5
{
    class Physics
    {
        public static void Iterate(double deltaTime, Vehicle[] vehicles)
        {
            for (int i = 0; i < vehicles.Length; i++)
            {
                //Accelration accumulated based on force generated by vehicle subtracted by drag experienced by the same vehicle
                vehicles[i].acceleration.x += (int)((vehicles[i].force.x - vehicles[i].drag.x) * deltaTime * 1.5f);

                //Clamp acceleration to max accelration value
                if (vehicles[i].acceleration.x > vehicles[i].maxAcceleration.x)
                {
                    vehicles[i].acceleration.x = vehicles[i].maxAcceleration.x;
                }

                //Updating position based on equation to solve for distance travelled for a given time, acceleration, and initial velocity
                vehicles[i].position += vehicles[i].velocity * deltaTime + vehicles[i].acceleration * 0.5f * deltaTime * deltaTime;

                //Updating final velocity due to accelration for next frame
                vehicles[i].velocity = vehicles[i].velocity + vehicles[i].acceleration * deltaTime;

                //Clamp acceleration to max acceleration value
                if (vehicles[i].velocity.x > vehicles[i].maxVelocity.x)
                {
                    vehicles[i].velocity.x = vehicles[i].maxVelocity.x;
                }
                else if (vehicles[i].velocity.x < 0)
                {
                    vehicles[i].velocity.x = 0;
                }
            }
        }
    }
}
